# Copyright 2022 Amazon.com and its affiliates; all rights reserved. 
# This file is Amazon Web Services Content and may not be duplicated or distributed without permission.

# TASK 1
WRONG_IP_ADDRESS_DESC="Wrong IP address"
WRONG_IP_ADDRESS_POINTS=-500

CORRECT_IP_ADDRESS_DESC="Correct IP address"
CORRECT_IP_ADDRESS_POINTS=1000

MONITORING_WEB_APP_UP_DESC="The web app is up"
MONITORING_WEB_APP_UP_POINTS=10

MONITORING_WEB_APP_DOWN_DESC="The web app is down"
MONITORING_WEB_APP_DOWN_POINTS=-10

TASK1_COMPLETE_DESC="Monitoring task completed"
TASK1_COMPLETE_POINTS=1000


# TASK 2
TASK2_COMPLETE_DESC="Successfully launched CloudShell"
TASK2_COMPLETE_POINTS=1000


# TASK 3
KEY_NOT_ROTATED_DESC="Access keys compromised"
KEY_NOT_ROTATED_POINTS=-10

KEY_ROTATED_DESC="Compromised access keys neutralized"
KEY_ROTATED_POINTS=1000


# TASK 4
THE_ANSWER_WRONG_DESC="You chose poorly"
THE_ANSWER_WRONG_POINTS=-5000

THE_ANSWER_CORRECT_DESC="42 is THE answer"
THE_ANSWER_CORRECT_POINTS=1000


# QUEST COMPLETION
QUEST_COMPLETE_DESC="Quest completed"
QUEST_COMPLETE_POINTS=10000

# QUEST COMPLETION BONUS POINTS
QUEST_COMPLETE_BONUS_DESC="Quest complete bonus points"
QUEST_COMPLETE_MULTIPLIER=10

